"use client";

import { useState } from "react";
import { Check, CircleSlash, Copy, Cpu, TriangleAlert, WifiOff } from "lucide-react";
import { notify } from "@/lib/notify";
import { AnswerBody } from "@/components/ask/AnswerBody";
import { ConfidenceBadge } from "@/components/ember/badges";
import { CitationChip } from "@/components/ember/CitationChip";
import { ErrorNotice, SkeletonLines } from "@/components/ember/states";
import type { AskState } from "@/hooks/use-ask-stream";
import { normalizeAnswer, usedAliases } from "@/lib/ai/citations";
import { cn } from "@/lib/utils";

const chip = "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs leading-5 whitespace-nowrap";

export function ModeBadge({ meta }: { meta: NonNullable<AskState["meta"]> }) {
  if (meta.mode === "ai") {
    return (
      <span className={cn(chip, "border-line-strong text-ink-muted")} title="Generated by the configured model from the retrieved passages">
        <Cpu className="size-3.5" strokeWidth={1.75} aria-hidden />
        AI answer · {meta.modelId?.replace(/^.*\//, "")}
      </span>
    );
  }
  if (meta.mode === "refusal") {
    return (
      <span className={cn(chip, "border-flame-core/35 text-flame-core")}>
        <CircleSlash className="size-3.5" strokeWidth={1.75} aria-hidden />
        Outside the evidence
      </span>
    );
  }
  return (
    <span
      className={cn(chip, "border-flame-micro/35 text-flame-micro")}
      title={meta.mode === "offline-precomputed" ? "A saved, cited answer generated earlier" : "The most relevant passages, shown verbatim"}
    >
      <WifiOff className="size-3.5" strokeWidth={1.75} aria-hidden />
      Offline mode · {meta.mode === "offline-precomputed" ? "saved answer" : "passages only"}
    </span>
  );
}

/** One question + its streamed answer, with provenance: mode, confidence, sources used, stripped citations. */
export function AnswerView({ state, onRetry, compact = false }: { state: AskState; onRetry?: () => void; compact?: boolean }) {
  const [copied, setCopied] = useState(false);
  const { meta, text, status } = state;
  const aliases = meta?.aliases ?? {};
  const used = state.done?.used ?? usedAliases(text, aliases);
  const sources = Array.from(new Map(used.map((a) => [aliases[a]?.sourceId, a])).entries()).filter(([id]) => id);
  const streaming = status === "streaming";

  const copy = async () => {
    const plain = normalizeAnswer(text).replace(/\[\[(S\d+)\]\]/g, (_, a: string) => (aliases[a] ? ` [${aliases[a].label}]` : ""));
    try {
      await navigator.clipboard.writeText(`Q: ${state.question}\n\n${plain}`);
      setCopied(true);
      notify("success", "Answer copied with its citations");
      setTimeout(() => setCopied(false), 1600);
    } catch {
      notify("error", "Could not copy to the clipboard");
    }
  };

  return (
    <article className="space-y-4" aria-busy={status === "loading" || streaming}>
      {meta ? (
        <div className="flex flex-wrap items-center gap-2">
          <ModeBadge meta={meta} />
          {meta.confidence !== "none" ? <ConfidenceBadge confidence={meta.confidence} /> : null}
          <span className="text-xs text-ink-faint">
            {meta.retrieval.passages} passages retrieved · {meta.retrieval.mode === "hybrid" ? "keyword + semantic search" : "keyword search"}
          </span>
        </div>
      ) : null}

      {meta?.notice ? <p className="text-xs text-flame-core">{meta.notice}</p> : null}

      {status === "loading" ? (
        <div className="space-y-2" role="status">
          <p className="text-xs text-ink-faint">Searching NASA records…</p>
          <SkeletonLines lines={compact ? 3 : 5} />
        </div>
      ) : null}

      {text ? <AnswerBody text={text} aliases={aliases} streaming={streaming} /> : null}

      {status === "error" ? (
        <ErrorNotice
          title="The answer could not be completed"
          body={
            <>
              {state.error}{" "}
              {onRetry ? (
                <button type="button" onClick={onRetry} className="text-flame-micro underline underline-offset-4">
                  Try again
                </button>
              ) : null}
            </>
          }
        />
      ) : null}

      {state.done?.flagged.length ? (
        <div className="flex gap-2 rounded-xl border border-flame-core/30 bg-flame-core/[0.06] p-3 text-xs text-ink-muted">
          <TriangleAlert className="mt-0.5 size-3.5 shrink-0 text-flame-core" strokeWidth={1.75} aria-hidden />
          <p>
            {state.done.invalid.length} citation{state.done.invalid.length === 1 ? "" : "s"} pointed at passages EMBER did not retrieve and{" "}
            {state.done.invalid.length === 1 ? "was" : "were"} removed. Treat these sentences with care:{" "}
            {state.done.flagged.map((s, i) => (
              <q key={i} className="mr-1 text-ink">
                {s}
              </q>
            ))}
          </p>
        </div>
      ) : null}

      {status === "done" && meta && meta.mode !== "refusal" ? (
        <footer className="flex flex-col gap-3 border-t border-line pt-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="min-w-0">
            <p className="mb-2 text-xs text-ink-faint">Sources used ({sources.length})</p>
            {sources.length ? (
              <div className="flex flex-wrap gap-1.5">
                {sources.map(([sourceId, alias]) => (
                  <CitationChip key={sourceId} sourceId={sourceId!} chunkId={aliases[alias].chunkId} page={aliases[alias].page} excerpt={aliases[alias].excerpt} />
                ))}
              </div>
            ) : (
              <p className="text-xs text-ink-muted">No passage was cited.</p>
            )}
          </div>
          <button
            type="button"
            onClick={copy}
            className="inline-flex h-9 shrink-0 items-center gap-1.5 self-start rounded-full border border-line-strong px-3.5 text-xs text-ink-muted transition-colors hover:border-white/25 hover:text-ink active:scale-[0.98]"
          >
            {copied ? <Check className="size-3.5" strokeWidth={1.75} aria-hidden /> : <Copy className="size-3.5" strokeWidth={1.75} aria-hidden />}
            {copied ? "Copied" : "Copy answer"}
          </button>
        </footer>
      ) : null}
    </article>
  );
}
